# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906b71b2d712fbb7ddad9067319bcccb127007164f818f9be5f237ca94a1c93ab5de2871670f1e09173dac5b456fa866bc5e5fccb59586d773aac68d1745bd7a

test:
  secret_key_base: 3fab7248577d688f7b6878c0b5a96f73b98dee5c3bd2c45a2feb26be684b1e0aa1e8848f63326383780ef09aaaf6af22d4b8550fe02a44cef46b96f3fac25037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
